### ISSUE TITLE
Is it possible with DataDirector ?

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#12]
Hello

I have two cases:

1. I have Customer class with some data fields and additional field called ExportFlag. Have for example 100 records but only 20 have the ExportFlag set to True. 
I want to setup export via DD but only for those records with ExportFlag == True.
Is it possible direct in DataDirector ?

2.  I have Product class and 100.000 products. I want to setup export the data for XML file. But I want to chunk this export and want that every file will have max. 1000 products. 
Is it possible with DD ?

**Comment by BlackbitNeueMedien** [comment]
1. Yes. Just set `ExportFlag=1` as SQL condition for the dataport
2. Yes. Use the built-in `Export raw data as XML` template for `result callback function`, change it so that the generated XML for the current item does not get appended to the complete XML but save it to `$params['transfer']->itemXML` array.
In the `result document action` use `array_chunk($params['transfer']->itemXML, 1000);` then you will have the XML chunks of max. 1000 items. Loop over those chunks, concatenate the XML for current chunk items, save to file. Depending on what you want to do with the generated files, you can copy some code from the `result document function` templates `Save as asset`, `Save as zip asset`, `Upload via FTP / FTPS`, `Upload via SFTP` or `Upload via AWS S3`.
