### ISSUE TITLE
Starting import manually does not work

### ISSUE THREAD

**Issue by iidaVaHa** [BlackbitDigitalCommerce/pimcore-data-director#127]
Data Director version 3.4.16

Starting import from Pimcore backend does not start the import. No errors are thrown either.

Executing import via CLI works perfectly fine, so is there some settings I'm missing on configuration that could cause the issue?

**Comment by BlackbitDevs** [comment]
Please check your `parameters.yaml` or the `parameters` section in `services.yaml` and look if you have configured `pimcore_executable_php` to a different value than `which php` gives you on CLI. In rare cases in 3.4 it can still happen that the wrong PHP version gets used, this is fixed in 3.5 - so if it does not work after you checked the YAML files, please try with version `3.5.x-dev`. If it works with this but you do not want to use an unstable version (which gets released next week if there isnÄt any critical bug discovered), please notify me, then I will backport the change for retrieving the PHP binary.

**Comment by BlackbitDevs** [comment]
@iidaVaHa Is fixed?
