### ISSUE TITLE
Wrong label for option ?

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#14]
![image](https://user-images.githubusercontent.com/7449124/155695559-36d30fd2-9884-41db-81b2-096c98399cce.png)

**Comment by BlackbitNeueMedien** [comment]
No, is really asset target folder. Asset source is not necessary because you have configured to extract data from existing Pimcore assets. 
Depending on target class it can make sense to configure `Asset target folder` here, e.g. when you want to import assets with the same filename but from a different location than the source assets.
