### ISSUE TITLE
Multivalue fields are not getting parsed (Unicode chars)

### ISSUE THREAD

**Issue by polargold-dev** [BlackbitDigitalCommerce/pimcore-data-director#191]
We are trying to import a few text fields from a XML file which include Unicode chars (German letters like: "öäü", for example).

If `Multivalue` is true they are not getting parsed like they do with the same setting off.

<img width="163" alt="unchecked" src="https://github.com/user-attachments/assets/97a3dfe0-6470-4a4c-a286-0585e94259be">

![checked](https://github.com/user-attachments/assets/17e0c1e8-6636-4990-ae7b-c998693921b5)

**Comment by polargold-dev** [comment]
Hi,
Why would you remove the Multi value feature?

As you can see on the screenshot below, the values in the arrays are not decoded correctly. for example, `/u2022` and `\t` can be found in the text.

Another Example of an output would be: `["Aktuelles zum K\u00fcndigungsrecht"]`

**Comment by BlackbitDevs** [comment]
> Why would you remove the Multi value feature? What are the alternatives to this feature in the future?

The alternative would be that `multiValue` always gets used. Because if there are multiple matching nodes, the current behaviour without `multiValue` is to take the first one, e.g.
```xml
 <Asset source="Productbenefit1_picture_www.miele.com/pmedia/06/Z13/20000093933-000-00_20000093933.png">
        <AssetProperty name="format">image/png</AssetProperty>
        <AssetProperty name="identifier">http://www.miele.com/pmedia/06/Z13/20000093933-000-00_20000093933.png</AssetProperty>
        <AssetProperty name="subject">feature picture</AssetProperty>
        <AssetProperty name="title">Pröductbenefit1_picture_www.miele.com/pmedia/06/Z13/20000093933-000-00_20000093933.jpg</AssetProperty>
    </Asset>
```
When you have item xpath `//Asset` and raw data field xpath `AssetProperty` the value is:
- without `multiValue`: image/png
  - this selects the inner value of the first found node. But this is not self-explaining
- with `multiValue`: 
```json
[
    {
        "@attributes": {
            "name": "format"
        },
        "_value": "image/png"
    },
    {
        "@attributes": {
            "name": "identifier"
        },
        "_value": "http://www.miele.com/pmedia/06/Z13/20000093933-000-00_20000093933.png"
    },
    {
        "@attributes": {
            "name": "subject"
        },
        "_value": "feature picture"
    },
    {
        "@attributes": {
            "name": "title"
        },
        "_value": "Pröductbenefit1_picture_www.miele.com/pmedia/06/Z13/20000093933-000-00_20000093933.jpg"
    }
]
```
  - this is more correct and if the `AssetProperty` nodes do not have attributes, the result is a simple array (as in your screenshot) and if there is only one node without any attributes, the result will be its value as a string
  - the only BC break would be if you have a single node which has attributes but you only want to get its value. But this should be possible to cover with a migration...

Back to your umlaut problem:
I have just tested with this XML file:
```xml
<Assets>
    <Asset>
        <AssetProperty>ömage/png</AssetProperty>
        <AssetProperty>Pröduct</AssetProperty>
    </Asset>
</Assets>
```

and I get:
<img width="286" alt="Bildschirmfoto 2024-11-19 um 14 11 56" src="https://github.com/user-attachments/assets/c878bdc9-f34f-4604-a9eb-0e0a5f78b4c3">

So looks good. And also some umlauts in your screenshot look good, so I tried to resize the column so that the "..." break is at the umlaut but still works:
<img width="242" alt="Bildschirmfoto 2024-11-19 um 14 20 40" src="https://github.com/user-attachments/assets/13bc974d-0975-46d0-90d7-824ead190ea1">

Could you send me an example file which does not work? If you do not want to publish this, you can send it to jan.walther@blackbit.de
