### ISSUE TITLE
Export data by tags as filter condition

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#195]
Is it possible to export objects by the tags as filter condition?
I have a tag on the object assigned, how can i export the object by this tag?
![image](https://github.com/user-attachments/assets/6ad1692f-c6e9-45bc-a6cb-22bd1ea89f5c)
The documentation has only example of importing tags: https://blackbitdigitalcommerce.github.io/pimcore-data-director/#tags
Thanks!

**Comment by BlackbitDevs** [comment]
Currently there is no convenience function to filter by tags in SQL condition. 2 options:
- In SQL condition add `id IN (SELECT cid FROM tags_assignments INNER JOIN tags ON tags_assignments.tagid=tags.id WHERE name='Austria')`
- we could add the above in SQL transpiling but I am currently not sure which syntax we could use (which cannot collide with a real data object field - `tag='Austria'` is not possible because `tag` is also a valid name for a data object field

**Comment by ascheider** [comment]
@BlackbitDevs Thanks for the example. This worked almost directly, you misspelled the tags_assignment table, but the idea was great.
I let the fully working example here, if someone later is searching for the solution

`object_localized_Product_de.id IN (SELECT cid FROM tags_assignment INNER JOIN tags ON tags_assignment.tagid=tags.id WHERE name='Schnittprofit')`
