### ISSUE TITLE
Importing files with glob expression (wildcards) - does not work

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#20]
My config is:
![image](https://user-images.githubusercontent.com/7449124/156160431-a79fe696-033d-4000-8a2f-1eead6ebe4db.png)

When I upload the file [SupplierProduct.xml ](url)into `/@DD/Supplier One/Import/` folder
DD do not start import automatically.

Is it a bug ?

**Comment by BlackbitNeueMedien** [comment]
What is `@DD`? Is this a Pimcore asset folder or a filesystem folder? If it is a Pimcore asset folder, which data director version are you using? Because I just implemented glob expression aka wildcard support for Pimcore asset files yesterday for version 2.8, see https://github.com/BlackbitDigitalCommerce/pimcore-data-director/issues/15#issuecomment-1054166903

If you are using the latest 2.8.x-dev or above version, then it is a bug.

**Comment by betterapp** [comment]
We do not use 2.8 and any dev version. 
We use 2.7.10

Question is: For which version this documentation is ?
https://pimcore.blackbit.de/Blackbit/1.pimcore/Handb%C3%BCcher/Ultima-Import-Bundle.pdf

Do you have any changelog file other then checking the commits ?

**Comment by BlackbitNeueMedien** [comment]
Documentation is currently not versioned. 
In documentation it is mentioned that glob expressions work - but in 2.7 this is only the case for file system folders.

**Comment by betterapp** [comment]
@BlackbitNeueMedien when will 2.8 tag be published for DD ? Soon or later ?

**Comment by betterapp** [comment]
Working with 2.8
