### ISSUE TITLE
Raw Fields IDs 1000+ dont fit the column width.

### ISSUE THREAD

**Issue by kaurov** [BlackbitDigitalCommerce/pimcore-data-director#48]
I have a dataport with source having many raw fields.
When the field ID is biggen then 1000 then the column is too narrow: I see only '1..'
And there is no ability to resize the column width.
And when I delete the field (e.g. 37), the next ID is generated not as smallest available (37) but MAX of existing fields (1256).

**Comment by kaurov** [comment]
![75fdbb0c-6e42-4480-8383-3d28aad0f884](https://user-images.githubusercontent.com/2579907/186689265-99643569-9efb-40b0-a883-3d2ce35fb284.png)

**Comment by BlackbitNeueMedien** [comment]
Is fixed in 3.2 - there you can resize the `#` column.

> And when I delete the field (e.g. 37), the next ID is generated not as smallest available (37) but MAX of existing fields (1256).
This is on purpose because otherwise when a field gets deleted and another one created, they would get the same field number. This might lead to confusion because in attribute mapping then the new field would be mapped where previously the old one was mapped. With completely new field numbers you have "Raw data field <deleted field number>" assigned in attribute mapping which is easily to spot and to fix.
