### ISSUE TITLE
Skipping items if key field is null does not work for path field

### ISSUE THREAD

**Issue by AndreasEisenbergerDGTLS** [BlackbitDigitalCommerce/pimcore-data-director#60]
It seems to me that if I set the path field as key attribute and then return null in the callback function it should skip that item.
But for me it doesnt. Can you confirm this?
Currently I am using version 3.0.12

If I set an object specific field as key attribute and return null it does skip that item ( but I think here youre info message is outdated: "Skipping item because raw data in all key columns is null") since you made that change in version 2.7.x.

Thanks in advance for your always helpful support

**Comment by BlackbitDevs** [comment]
Yes, this was a bug in `3.0.12` which got fixed in 3.2. Returning `null` for `path` was converted to an empty string back then. For this reason the skipping did not work. Please update.

In addition: in recent stable version the logged message is `Skipping item because raw data in at least one key column is null`.
