### ISSUE TITLE
DataObjectEvents::PRE_ADD event

### ISSUE THREAD

**Issue by ascheider** [BlackbitDigitalCommerce/pimcore-data-director#87]
Pimcore has many standard data object events, where things can be manipulated.
We have event for the customer, where we use pre add event, to generate uuid.
This is done one time on creation.
If we import objects with data director, the uuid is missing, because the event is not triggered from data director.
Unfortunately i can not use callback function to generate uuid's like Uid::v4()->__toString(), because the will be overwritten if i execute import more than once.
is it possible to add/fire pre add event, if object is fresh created via data director?
Thanks!

**Comment by BlackbitDevs** [comment]
Which Pimcore event exactly do you mean? Currently the `preAdd`, `preUpdate` and `postUpdate` events for the corresponding target element type get triggered.

**Comment by BlackbitDevs** [comment]
Correct, the reason is the optimized saving - only mapped import fields get saved while Pimcore always saves all fields (which makes it slow). Now there are 2 options to get the UUID saved:
1. Map it in the dataport. You can enable the checkbox "Do not overwrite if already filled" to only generate it at the beginning - or you check for $params['currentObjectData']['id']: if it is empty, a new object got created instead of updating an existing one.
2. Enable "Compatibility mode" in the advanced dataport settings. With this the default saving mechanism of Pimcore will get used - resulting in less performance but fully compliant processing.

**Comment by ascheider** [comment]
@BlackbitDevs Nice. Thanks. I will try it 👍
